
parameters: {}

variables: {
  ProjectName: '[x={ $Node.Project }=]',
  Project_Ensure: '[x={ $Node.ProjectPresence }=]'  
}

resources:

  - name: Project
    type: AzureDevOpsDsc/AzDoProject
    postExecutionScript: if ($Project_Ensure -eq 'Absent') { Stop-TaskProcessing }
    properties:
      projectName: $ProjectName
      projectDescription: $ProjectDescription
      visibility: private
      SourceControlType: Git
      ProcessTemplate: Agile
      Ensure: $( if ([string]::IsNullOrEmpty($Project_Ensure)) { 'Present' } else { $Project_Ensure } )

  - name: Project Services
    type: AzureDevOpsDsc/AzDoProjectServices
    dependsOn: 
      - AzureDevOpsDsc/AzDoProject/Project
    properties:
      projectName: $ProjectName
      GitRepositories: $( if ([string]::IsNullOrEmpty($Project_Service_GitRepositories)) { 'disabled' } else { $Project_Service_GitRepositories } )
      BuildPipelines: $( if ([string]::IsNullOrEmpty($Project_Service_BuildPipelines)) { 'disabled' } else { $Project_Service_BuildPipelines } )
      AzureArtifact: $( if ([string]::IsNullOrEmpty($Project_Service_AzureArtifact)) { 'disabled' } else { $Project_Service_AzureArtifact } )
      WorkBoards: $( if ([string]::IsNullOrEmpty($Project_Service_WorkBoards)) { 'disabled' } else { $Project_Service_WorkBoards } )
      TestPlans: $( if ([string]::IsNullOrEmpty($Project_Service_TestPlans)) { 'disabled' } else { $Project_Service_TestPlans } )
