#
# Module manifest for module 'azdo-dsc-lcm'
#
# Generated by: Michael Zanatta
#
# Generated on: 10/10/2024
#

@{

    Path = "./azdo-dsc-lcm.psd1"
    ModuleManifest = "./azdo-dsc-lcm.psd1"
    # Script module or binary module file associated with this manifest.

}

